---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: (\.html$|^workflow/scripts/count/MergeTrimReads\.py$|^workflow/scripts/count/library\.py$|^workflow/scripts/count/FastQ2doubleIndexBAM\.py$|^workflow/scripts/count/MergeTrimReadsBAM\.py$)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']

  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0a3
    hooks:
      - id: isort
        args: ['--profile', 'black']

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/snakemake/snakefmt
    rev: v1.1.0
    hooks:
      - id: snakefmt


ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: 'chore(deps) pre-commit autoupdate'
  autoupdate_schedule: monthly
  skip: []
  submodules: false
